class Sizes:
	CHARACTER_PANEL_WIDTH = 340

	PORTRAIT_WIDTH = 180
	PORTRAIT_HEIGHT = 240

	LEVEL_BADGE_SIZE = 28

	SKILLS_MIN_HEIGHT = 72

	PARTY_PORTRAIT_SIZE = 36
	PARTY_HEALTH_HEIGHT = 4

	PARTY_MEMBER_WIDTH = 36
	PARTY_MEMBER_HEIGHT = 44
	PARTY_SECTION_HEIGHT = 60

	CARD_WIDTH = 180
	CARD_IMAGE_HEIGHT = 120

	ICON_SMALL = 16
	ICON_MEDIUM = 24
	ICON_LARGE = 32

	WINDOW_WIDTH = 1600
	WINDOW_HEIGHT = 960

	HEALTH_BAR_HEIGHT = 18
